language: go

go:
  - 1.7
  - 1.8
  - tip

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database qgtest;' -U postgres
  - cat schema.sql | psql -U postgres -d qgtest

script:
  - go get -u github.com/mattn/gom 
  - gom install
  - go test -v
