language: go

go:
  - 1.7
  - 1.8
  - tip

addons:
  postgresql: "9.5"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - psql -c 'create database qgtest;' -U postgres
  - cat schema.sql | psql -U postgres -d qgtest

script:
  - go test -v
